myproject/apps/admintools/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('apps.admintools.views',
	url(r'^suggestions/(?P<sg_pk>[^/]+)/approve/$', 'suggestions_approve'),
	url(r'^suggestions/(?P<sg_pk>[^/]+)/reject/$', 'suggestions_reject'),
	url(r'^suggestions/(?P<sg_pk>[^/]+)/$', 'suggestions_check'),
	url(r'^suggestions/$', 'suggestions'),
	url(r'^emailmanager/$', 'emailman_view'),
	url(r'^emailmanager/getemails/$', 'get_emails'),
	# url(r'^$', 'admintools_view'),
)

myproject/myproject/urls.py
from django.conf.urls import patterns, include, url
from myproject.forms import *

from registration.forms import RegistrationFormUniqueEmail

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

# moderation
# from moderation.helpers import auto_discover as moderation_auto_discover
# moderation_auto_discover()




# Examples:
# url(r'^$', 'myproject.views.home', name='home'),
# url(r'^myproject/', include('myproject.foo.urls')),
urlpatterns = patterns('',
	# Uncomment the admin/doc line below to enable admin documentation:
	url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

	# Uncomment the next line to enable the admin:
	url(r'^admin/', include(admin.site.urls)),

	(r'^grappelli/', include('grappelli.urls')),


	url(r'^profile/register/$', 'registration.views.register',
		{'form_class': RegistrationFormUniqueEmail,
		 'backend': 'registration.backends.default.DefaultBackend'},
		 name='registration_register'),

	#django-registration
	(r'^profile/', include('registration.backends.default.urls'), {"extra_context": {}}),
)

#Statics
urlpatterns += patterns('myproject.views',
	url(r'^(terms)/$', 'static_pages', {"extra_context": {}}, name='terms'),
	url(r'^(about)/$', 'static_pages', {"extra_context": {}}, name='aboutus'),
	url(r'^(disclaimer)/$', 'static_pages', {"extra_context": {}}, name='disclaimer'),
	url(r'^(privacypolicy)/$', 'static_pages', {"extra_context": {}}, name='privacy'),
	url(r'^(sponsorship)/$', 'static_pages', {"extra_context": {}}, name='sponsorship'),
	url(r'^(contactus)/$', 'static_pages', {"extra_context": {}}, name='contactus'),
)



# Homepage
urlpatterns += patterns('myproject.views',
	url(r'^$', 'homepage', {"extra_context": {}}, name='homepage'),
)

urlpatterns += patterns('apps.authentication.views',
	url(r'^recovery/', 'recovery'),
)

# Search Results page
urlpatterns += patterns('',
	url(r'^search/', include('apps.search.urls'), {"extra_context": {}}),
)

# Company profiles
urlpatterns += patterns('',
	url(r'^company/', include('apps.company_profile_edit.urls'), {"extra_context": {}}),
)

# User profiles
urlpatterns += patterns('',
	url(r'^users/', include('apps.authentication.urls'), {"extra_context": {}}),
)

# Ads
urlpatterns += patterns('',
	url(r'^msadtrackr/', include('apps.ad_interface.urls'), {"extra_context": {}}),
)


# Admin tools
urlpatterns += patterns('',
	url(r'^admintools/', include('apps.admintools.urls'), {"extra_context": {}}),
)



# ... serving media on local server
from django.conf import settings

if settings.LOCAL_SERVER:
	# user uploaded files (images, css, javascript, etc.)
	urlpatterns += patterns('',
		(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
		'document_root': settings.MEDIA_ROOT}))

myproject/apps/admintools/models.py
from django.db import models

# Create your models here.

myproject/apps/company_profile_edit/models.py
from django.db import models
import reversion
from django.db.models.signals import post_save
from apps.search.models import Company



class VersionApprove(models.Model):
    revision = models.ForeignKey('reversion.Revision')  # This is required

    is_approved_CHOICES = ((1, 'Approved'),
							(0, 'Pending'),
							(-1, 'Rejected'),)

    is_approved = models.SmallIntegerField(choices=is_approved_CHOICES, default=1)


def create_versionapprove(**kwargs):
	"""When creating a new user, make a profile for him or her."""
	# created = kwargs["created"]

	r = kwargs["revision"]
	if not VersionApprove.objects.filter(revision=r):
		VersionApprove(revision=r).save()

reversion.post_revision_commit.connect(create_versionapprove)



def comp_finder(instances):
	for i in instances:
		if isinstance(i, Company):
			return i
	return None

def auto_approve_versions(sender, **kwargs):
	pass
	versions = kwargs["versions"]
	revision = kwargs["revision"]
	instances = kwargs["instances"]
	company = instances[-1]
	if company == None:
		return

	if not revision.user.userprofile.permission_for_realtime_edit(company):
		# raise Exception
		latest_admin_approved = reversion.models.Version.objects.get_for_object(company).filter(revision__versionapprove__is_approved=1).order_by('-revision__date_created')[0]
		latest_admin_approved.revision.revert()
		# raise Exception("%s"%latest_admin_approved.revision.versionapprove.is_approved)


reversion.post_revision_commit.connect(auto_approve_versions)

myproject/apps/admintools/forms.py
from django import forms
import datetime

from apps.search.models import Company

# IS_FILTER_CHIOCES


class SinceDateForm(forms.Form):
	since = forms.DateField(initial=(datetime.date.today() - datetime.timedelta(7)), required=False)
	comps = forms.ModelMultipleChoiceField(required=False ,queryset=Company.objects.order_by('ticker_symbol'), widget=forms.SelectMultiple(attrs={'placeholder':'Select Companies',\
	 'class':'offset1 span6'}))
	# is_filter = forms.Radio

myproject/apps/admintools/views.py
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.shortcuts import render_to_response, get_object_or_404
# from reversion.helpers import generate_patch_html

from django.views.decorators.csrf import csrf_protect
from django.contrib.auth.decorators import login_required
from django.template import RequestContext

from django.contrib.auth.models import User
from forms import *

from apps.company_profile_edit.models import VersionApprove
from apps.search.models import Company
import reversion

import datetime

import csv

from django.db.models import Q



def list_in_list_search(qs, args):
	'''(qs, *args)
	args = [(whichone, [data]), (whichone, [data])]'''
	for whichone, data in args:
		for i, item in enumerate(data):
			try:
				q = q | Q(**{whichone+'__exact':item})
			except:
				q = Q(**{whichone+'__exact':item})


	try: return qs.filter(q)
	except: return qs




@csrf_protect
@login_required
def emailman_view(request, extra_context={}):
	
	initialdate=(datetime.date.today() - datetime.timedelta(7))

	user = request.user

	if not user.is_authenticated() and not user.is_staff and not user.is_superuser:
		raise Http404



	args = {'title':"%s's admintools"%user.username, 'sinceform':SinceDateForm, 'initialdate': initialdate.isoformat()}
	args.update(extra_context)

	return render_to_response('admintools/emailman.html', args, context_instance=RequestContext(request))


@csrf_protect
@login_required
def get_emails(request, extra_context={}):
	is_filter = request.GET.get('is_filter')
	filter_date = request.GET.get('filter_date') == 'yes'
	filter_comps = request.GET.get('filter_comps') == 'yes'
	dont_include_comp_users = request.GET.get('include_comp_users') != 'yes'

	qs = User.objects.all()

	if is_filter != 'all':
		sdf = SinceDateForm(request.GET)
		if sdf.is_bound and sdf.is_valid():
			# filter by date
			if filter_date:
				date = sdf.cleaned_data.get('since')
				qs = qs.filter(date_joined__gte = date)
			# filter by liked company
			if filter_comps:
				#raise Exception
				comps = sdf.cleaned_data.get('comps')
				qs = list_in_list_search(qs, [('userprofile__tracked_companies', comps)])

	if dont_include_comp_users:
		qs = qs.filter(userprofile__is_company_user__isnull=True)



	response = HttpResponse(mimetype='text/csv')
	response['Content-Disposition'] = 'attachment; filename=emails.csv'

	writer = csv.writer(response)
	writer.writerow(['Username', 'Email', 'Date joined', 'Type'])


	for usr in qs:
		s = ''
		for tpe in usr.userprofile.type_of_investor.all():
			s+= '%s, '%tpe
		
		writer.writerow([usr.username ,usr.email, usr.date_joined.date().isoformat(), s])

	# raise Exception
	return response

@csrf_protect
@login_required
def suggestions(request, extra_context={}):

	user = request.user

	if not user.is_authenticated() or not user.is_staff:
		raise Http404



	args = {'submissions':reversion.models.Revision.objects.exclude(comment="Initial version.").exclude(user=None).order_by('-date_created'), 'title':'Suggestions'}
	args.update(extra_context)

	return render_to_response('admintools/suggestions.html', args, context_instance=RequestContext(request))


def comp_finder(versions):
	for i in versions:
		if isinstance(i.object, Company):
			return i
	return None


@csrf_protect
@login_required
def suggestions_check(request, sg_pk, extra_context={}):

	user = request.user

	if not user.is_authenticated() or not user.is_staff:
		raise Http404

	sg = get_object_or_404(reversion.models.Revision, pk=sg_pk)
	company = comp_finder(sg.version_set.all()).object
	latest_admin_approved = reversion.models.Version.objects.get_for_object(company).filter(revision__versionapprove__is_approved=1).order_by('-revision__date_created')[0]

	diff_list = []
	for versionSG, versionAdminApproved in zip(sg.version_set.order_by('content_type','object_id'), latest_admin_approved.revision.version_set.order_by('content_type','object_id')):
		# get the old and the new value
		for field in versionSG.field_dict:
			new_value = versionSG.field_dict.get(field)
			old_value = versionAdminApproved.field_dict.get(field)

			# lists might get out of order
			try:
				new_value = str(new_value.sort())
				old_value = str(old_value.sort())
			except:
				pass
			if field not in {'edit_date', 'id'} and new_value != old_value:
				diff_list.append((versionSG.object, field, new_value, old_value))
				#raise Exception
				

	url_this_version = "/admin/search/company/%s/history/%s/"%(company.pk, comp_finder(sg.version_set.all()).pk)
	url_approved_version = "/admin/search/company/%s/history/%s/"%(company.pk, latest_admin_approved.pk)

	hide_reject = (sg.versionapprove_set.all()[0].is_approved == 1)

	args = {'title':sg.comment, 'url_this_version':url_this_version, 'url_approved_version':url_approved_version, 'hide_reject':hide_reject, 'diffs':diff_list}
	args.update(extra_context)

	return render_to_response('admintools/suggestions_check.html', args, context_instance=RequestContext(request))


@csrf_protect
@login_required
def suggestions_approve(request, sg_pk, extra_context={}):

	user = request.user

	if not user.is_authenticated() or not user.is_staff:
		raise Http404

	sg = get_object_or_404(reversion.models.Revision, pk=sg_pk)
	# revision.add_meta(VersionApprove, is_approved=1)

	va = sg.versionapprove_set.all()[0]
	va.is_approved = 1
	va.save()
	sg.revert()

	return HttpResponseRedirect('/admintools/suggestions/')


@csrf_protect
@login_required
def suggestions_reject(request, sg_pk, extra_context={}):

	user = request.user

	if not user.is_authenticated() or not user.is_staff:
		raise Http404

	sg = get_object_or_404(reversion.models.Revision, pk=sg_pk)
	# revision.add_meta(VersionApprove, is_approved=1)

	va = sg.versionapprove_set.all()[0]
	va.is_approved = -1
	va.save()

	return HttpResponseRedirect('/admintools/suggestions/')

myproject/apps/admintools/templates/admintools/emailman.html
{% extends "base.html" %}
{% load staticfiles %}

{% block CSS %}
<link href="{% static 'stylesheets/datepicker.css' %}" rel="stylesheet">
<link href="{% static 'stylesheets/select2.css' %}" rel="stylesheet" type="text/css">	
{% endblock CSS %}

{% block content %}
<div class="container">
	<div class="row-fluid">
		<div class="span12 well">
			<h3>Email Management</h3>
			
			<form action="getemails/" method="get">
				<div class="row-fluid">
					<div class="span12">
						<label for="is_filter_1" class="radio"><input type="radio" name="is_filter" id="is_filter_1" value="all" checked> Get a list of all users</label>
						<hr>
						<label for="is_filter_2" class="radio"><input type="radio" name="is_filter" id="is_filter_2" value="filter"> Advanced</label>
					</div>
				</div>
				<span id="advanced">
				<div class="row-fluid">
					<div class="span11 offset1">
						<label for="filter_date" class="checkbox"><input type="checkbox" name="filter_date" id="filter_date" value="yes"> Filter by date</label>
						<p class="offset1">Enter the date (by default it is a week ago)</p>
						<div class="input-append date datepicker offset1" data-date="{{ initialdate }}" id="select_date" data-date-format="yyyy-mm-dd">
							{{ sinceform.since }}
							<span class="add-on"><i class="icon-calendar"></i></span>
						</div>
					</div>
				</div>

				<div class="row-fluid">
					<div class="span11 offset1">
						<label for="filter_comps" class="checkbox"><input type="checkbox" name="filter_comps" id="filter_comps" value="yes"> Filter by liked companies</label>
						<span id="select_comps"><p class="offset1">Select the companies</p>
						{{ sinceform.comps }}</span>
					</div>
				</div>
				</span>


				<div class="row-fluid">
					<div class="span12">
						<hr>
						<label for="include_comp_users" class="checkbox"><input type="checkbox" name="include_comp_users" id="include_comp_users" value="yes"> Include company users?</label>
						<input class="btn btn-primary" type="submit">
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock content %}


{% block JS %}
	<script type="text/javascript" src="{% static 'javascript/select2.js' %}"></script>
	<script type="text/javascript" src="{% static 'javascript/bootstrap-datepicker.js' %}"></script>
{% endblock JS %}

{% block jQuery %}
<script type="text/javascript">
	function selectify () {
		if (($("body").width() > 767)){
			$("select").not(".not-select2").select2();
		} else if(!( (/iPhone|iPod|iPad|Android|BlackBerry/).test(navigator.userAgent) )){
			$("select").not(".not-select2").select2();
		}
	}
	$(document).ready(function() {
		selectify();
		$('.datepicker').datepicker();

		if ($("#is_filter_1").prop('checked')){
			$("#advanced input").prop({"disabled": true});
			$("#advanced select").select2("disable");
		}


		$("#is_filter_1").change(function(){
			if ($(this).prop('checked')){
				$("#advanced input").prop({"disabled": true});
				$("#select_comps select").select2("disable");
			}
		});

		$("#is_filter_2").change(function(){
			if ($(this).prop('checked')){
				$("#advanced input").not("#select_date input, #select_comps select").prop({"disabled": false});
				if ($("#filter_date").prop('checked')){
					$("#select_date input").prop({"disabled": false});
				} else{
					$("#select_date input").prop({"disabled": true});
				}

				if ($("#filter_comps").prop('checked')){
					$("#select_comps input").prop({"disabled": false});
					$("#select_comps select").select2("enable");
				} else{
					$("#select_comps input").prop({"disabled": true});
					$("#select_comps select").select2("disable");
				}

			}
		});



		$("#filter_date").change(function(){
			if ($(this).prop('checked')){
				$("#select_date input").prop({"disabled": false});
			} else{
				$("#select_date input").prop({"disabled": true});
			}
		});

		$("#filter_comps").change(function(){
			if ($(this).prop('checked')){
				$("#select_comps input").prop({"disabled": false});
				$("#select_comps select").select2("enable");
			} else{
				$("#select_comps input").prop({"disabled": true});
				$("#select_comps select").select2("disable");
			}
		});

	});
	
</script>
	
{% endblock jQuery %}

myproject/apps/admintools/templates/admintools/suggestions.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
<div class="container">
	<div class="row-fluid">
		<div class="span12">
			<table id="change-history" class="table table-hover">
                    <thead>
                        <tr>
                            <th scope="col">Date/time</th>
                            <th scope="col">User</th>
                            <th scope="col">Comment</th>
                            <th scope="col">Approval status</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for submission in submissions %}
                            <tr class="
                            {% if submission.versionapprove_set.all.0.is_approved == 1 %}
                                success
                            {% elif submission.versionapprove_set.all.0.is_approved == 0 %}
                                warning
                            {% else %}
                                error
                            {% endif %}
                            ">
                                <td scope="row"><strong><a href="{{submission.pk}}">{{submission.date_created}}</a></strong></td>
                                <td>
                                    {% if submission.user %}
                                        {{submission.user.username}}
                                        {% if submission.user.first_name %} ({{submission.user.first_name}} {{submission.user.last_name}}){% endif %}
                                    {% endif %}
                                </td>
                                <td>{{submission.comment|linebreaksbr|default:""}}</td>
                                <td>{{submission.versionapprove_set.all.0.get_is_approved_display }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>

		</div>
	</div>
</div>
{% endblock content %}

myproject/apps/admintools/templates/admintools/suggestions_check.html
{% extends "base.html" %}
{% load staticfiles %}


{% block content %}
<div class="container">
	<div class="row-fluid">
		<div class="span12">
			<h2>Review the difference</h2>
			<h3>Changes:</h3>
			<table class="table table-striped table-hover table-bordered">
				<thead>
					<tr>
						<th>Object</th>
						<th>Field</th>
						<th>New value</th>
						<th>Old Value</th>
					</tr>
				</thead>
				<tbody>
				{% for diff in diffs %}
					<tr>
						<td>{{ diff.0 }}</td>
						<td>{{ diff.1 }}</td>
						<td>{{ diff.2 }}</td>
						<td>{{ diff.3 }}</td>
					</tr>
				{% empty %}
					<tr class="info"><td colspan="4">This version is the same as the latest admin approved one</td></tr>
				{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span12">
			<!-- <div class="btn-group">
				<a class="btn btn-info" href="{{ url_this_version }}" target="_blank">Go to admin of this suggestion</a>
				<a class="btn btn-primary" href="{{ url_approved_version }}" target="_blank">Go to admin of the latest approved entry</a>
			</div>
			<br>
			<br> -->
			{% if not hide_reject %}
			<div class="btn-group">
				<a class="btn btn-large btn-success" href="approve/">Approve</a>
				<a class="btn btn-large btn-danger" href="reject/">Reject</a>
			</div>
			{% endif %}
		</div>
	</div>
</div>
{% endblock content %}