myproject/apps/search/urls.py
from django.conf.urls import patterns, include, url
# from myproject.forms import *


urlpatterns = patterns('apps.search.views',
	url(r'^$', 'search'),
)

myproject/myproject/urls.py
from django.conf.urls import patterns, include, url
from myproject.forms import *

from registration.forms import RegistrationFormUniqueEmail

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

# moderation
# from moderation.helpers import auto_discover as moderation_auto_discover
# moderation_auto_discover()




# Examples:
# url(r'^$', 'myproject.views.home', name='home'),
# url(r'^myproject/', include('myproject.foo.urls')),
urlpatterns = patterns('',
	# Uncomment the admin/doc line below to enable admin documentation:
	url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

	# Uncomment the next line to enable the admin:
	url(r'^admin/', include(admin.site.urls)),

	(r'^grappelli/', include('grappelli.urls')),


	url(r'^profile/register/$', 'registration.views.register',
		{'form_class': RegistrationFormUniqueEmail,
		 'backend': 'registration.backends.default.DefaultBackend'},
		 name='registration_register'),

	#django-registration
	(r'^profile/', include('registration.backends.default.urls'), {"extra_context": {}}),
)

#Statics
urlpatterns += patterns('myproject.views',
	url(r'^(terms)/$', 'static_pages', {"extra_context": {}}, name='terms'),
	url(r'^(about)/$', 'static_pages', {"extra_context": {}}, name='aboutus'),
	url(r'^(disclaimer)/$', 'static_pages', {"extra_context": {}}, name='disclaimer'),
	url(r'^(privacypolicy)/$', 'static_pages', {"extra_context": {}}, name='privacy'),
	url(r'^(sponsorship)/$', 'static_pages', {"extra_context": {}}, name='sponsorship'),
	url(r'^(contactus)/$', 'static_pages', {"extra_context": {}}, name='contactus'),
)



# Homepage
urlpatterns += patterns('myproject.views',
	url(r'^$', 'homepage', {"extra_context": {}}, name='homepage'),
)

urlpatterns += patterns('apps.authentication.views',
	url(r'^recovery/', 'recovery'),
)

# Search Results page
urlpatterns += patterns('',
	url(r'^search/', include('apps.search.urls'), {"extra_context": {}}),
)

# Company profiles
urlpatterns += patterns('',
	url(r'^company/', include('apps.company_profile_edit.urls'), {"extra_context": {}}),
)

# User profiles
urlpatterns += patterns('',
	url(r'^users/', include('apps.authentication.urls'), {"extra_context": {}}),
)

# Ads
urlpatterns += patterns('',
	url(r'^msadtrackr/', include('apps.ad_interface.urls'), {"extra_context": {}}),
)


# Admin tools
urlpatterns += patterns('',
	url(r'^admintools/', include('apps.admintools.urls'), {"extra_context": {}}),
)



# ... serving media on local server
from django.conf import settings

if settings.LOCAL_SERVER:
	# user uploaded files (images, css, javascript, etc.)
	urlpatterns += patterns('',
		(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
		'document_root': settings.MEDIA_ROOT}))

myproject/apps/ad_interface/models.py
from django.db import models
from apps.search.models import Commodity, Company

import random



def multi_ad_picker(primary_key, number):
	ads = rsample((TypeOfAd.objects.get(pk=primary_key)).ad_set.all(), number)
	for ad in ads:
		ad.num_impressions += 1
		ad.save()
	return ads


def single_ad_picker(primary_key):
	try:
		ad = random.choice(TypeOfAd.objects.get(pk=primary_key).ad_set.all())
		ad.num_impressions += 1
		ad.save()
		return ad
	except IndexError:
		return None


def rsample(l, num):
	for i in range(num, -1, -1):
		try:
			s = random.sample(l, i)
			return s
		except ValueError: pass
	return []



class TypeOfAd(models.Model):
	type_name = models.CharField(max_length=25)

	optimal_height = models.IntegerField()
	optimal_width = models.IntegerField()

	def __unicode__(self):
		return unicode(self.type_name)
	


class Ad(models.Model):

	ad_name = models.CharField(max_length=25)

	picture = models.ImageField(upload_to='assetsd')

	type_of_ad = models.ManyToManyField(TypeOfAd)

	commodities = models.ManyToManyField(Commodity, blank=True, null=True)
	sponsor = models.ForeignKey(Company, blank=True, null=True)

	link = models.URLField(blank=True)


	num_impressions = models.IntegerField(default=0)
	num_clicks = models.IntegerField(default=0)

	hover_text = models.CharField(max_length=25, blank=True)

	class Meta:
		verbose_name_plural = 'Ads'

	def __unicode__(self):
		return unicode(self.ad_name)

myproject/apps/search/forms.py
from django import forms
from models import Commodity, Property


class FinancialInfoSearchForm(forms.Form):
	wg_min = forms.TextInput(attrs={'placeholder':'min', 'class':'span6', 'pattern':'\d*(\.\d+)?',\
	 'data-validation-pattern-message':'Must be a number or decimal'})
	wg_max = forms.TextInput(attrs={'placeholder':'max', 'class':'span6', 'pattern':'\d*(\.\d+)?',\
	 'data-validation-pattern-message':'Must be a number or decimal'})

	wg_low = forms.TextInput(attrs={'placeholder':'low', 'class':'span6', 'pattern':'\d*(\.\d+)?',\
	 'data-validation-pattern-message':'Must be a number or decimal'})
	wg_high = forms.TextInput(attrs={'placeholder':'high', 'class':'span6', 'pattern':'\d*(\.\d+)?',\
	 'data-validation-pattern-message':'Must be a number or decimal'})


	price_min = forms.DecimalField(widget=wg_min, required=False)
	price_max = forms.DecimalField(widget=wg_max, required=False)

	vol_min = forms.DecimalField(widget=wg_min, required=False)
	vol_max = forms.DecimalField(widget=wg_max, required=False)

	marketcap_min = forms.DecimalField(widget=wg_min, required=False)
	marketcap_max = forms.DecimalField(widget=wg_max, required=False)

	shouts_min = forms.DecimalField(widget=wg_min, required=False)
	shouts_max = forms.DecimalField(widget=wg_max, required=False)

	fifty_low_min = forms.DecimalField(widget=wg_low, required=False)

	fifty_high_max = forms.DecimalField(widget=wg_high, required=False)


class FinancialInfoDisabledForm(forms.Form):
	wg_min = forms.TextInput(attrs={'placeholder':'min', 'class':'span6', 'disabled':'disabled'})
	wg_max = forms.TextInput(attrs={'placeholder':'max', 'class':'span6', 'disabled':'disabled'})

	wg_low = forms.TextInput(attrs={'placeholder':'low', 'class':'span6', 'disabled':'disabled'})
	wg_high = forms.TextInput(attrs={'placeholder':'high', 'class':'span6', 'disabled':'disabled'})

	price_min = forms.DecimalField(widget=wg_min, required=False)
	price_max = forms.DecimalField(widget=wg_max, required=False)

	vol_min = forms.DecimalField(widget=wg_min, required=False)
	vol_max = forms.DecimalField(widget=wg_max, required=False)

	marketcap_min = forms.DecimalField(widget=wg_min, required=False)
	marketcap_max = forms.DecimalField(widget=wg_max, required=False)

	shouts_min = forms.DecimalField(widget=wg_min, required=False)
	shouts_max = forms.DecimalField(widget=wg_max, required=False)

	fifty_low_min = forms.DecimalField(widget=wg_low, required=False)

	fifty_high_max = forms.DecimalField(widget=wg_high, required=False)


class PropertySearchForm(forms.ModelForm):
	def __init__(self, *args, **kwargs):
		super(PropertySearchForm, self).__init__(*args, **kwargs)
		# self.fields['commodities'].required = False

		self.fields['status'].required = False
	class Meta:
		model = Property
		fields = ('status',)# 'commodities')
		# widgets = {'commodities': forms.widgets.SelectMultiple(attrs={'class': 'span12'})}

myproject/apps/search/views.py
from django.template import RequestContext
from django.views.decorators.csrf import csrf_protect
from myproject.forms import NavBarSearch

from models import *
from apps.search.forms import *
from django.shortcuts import render_to_response

from haystack.query import SearchQuerySet, EmptySearchQuerySet, SQ


from apps.ad_interface.models import *


select2_dict = {'regions': Region.objects.all(), 'countries': Country.objects.all(), 'states': State.objects.all(), 'commodities': Commodity.objects.all()}


# def status_decoder(coded):
# 	if not coded: return set([''])
# 	ret_set = set()
# 	rec_set = status_decoder(coded[1:])
# 	for item in rec_set:
# 		ret_set.update([coded[0]+item, '_'+item])
# 	return ret_set


def financial_info_search(sqs, fin_form):
	fin_form_clean = fin_form.cleaned_data
	price_min = fin_form_clean.get('price_min')
	price_max = fin_form_clean.get('price_max')
	vol_min = fin_form_clean.get('vol_min')
	vol_max = fin_form_clean.get('vol_max')
	marketcap_min = fin_form_clean.get('marketcap_min')
	marketcap_max = fin_form_clean.get('marketcap_max')
	shouts_min = fin_form_clean.get('shouts_min')
	shouts_max = fin_form_clean.get('shouts_max')
	fifty_low_min = fin_form_clean.get('fifty_low_min')
	fifty_high_max = fin_form_clean.get('fifty_high_max')

	try:
		price_min = int(10000*price_min)
	except: pass
	try:
		price_max = int(10000*price_max)
	except: pass

	try:
		fifty_low_min = int(10000*fifty_low_min)
	except: pass
	try:
		fifty_high_max = int(10000*fifty_high_max)
	except: pass

	kwargs = financial_info_search_logic(price_min, price_max, 'price')
	kwargs.update(financial_info_search_logic(vol_min, vol_max, 'volume'))
	kwargs.update(financial_info_search_logic(marketcap_min, marketcap_max, 'market_cap'))
	kwargs.update(financial_info_search_logic(shouts_min, shouts_max, 'outstanding'))
	kwargs.update(financial_info_search_logic(fifty_low_min, fifty_high_max, 'fiftytwo_week_low', 'fiftytwo_week_high'))

	return sqs.filter(**kwargs)

def financial_info_search_logic(num_min, num_max, whichone, whichone2='BIGALOW'):
	if whichone2 == 'BIGALOW':
		whichone2 = whichone

	if not num_min and not num_max:
		return {}
	elif num_min and not num_max:
		return {(whichone + '__gte'):num_min}
	elif not num_min and num_max:
		return {(whichone2 + '__lte'):num_max}
	else:
		if whichone == whichone2:
			return {(whichone + '__range'):[num_min, num_max]}
		else:
			return {(whichone + '__gte'):num_min, (whichone2 + '__lte'):num_max}


def list_in_list_search(sqs, args):
	'''(sqs, *args)
	args = [(whichone, [data]), (whichone, [data])]'''
	for whichone, data in args:
		for i, item in enumerate(data):
			try:
				sq = sq | SQ(**{whichone+'__exact':item})
			except:
				sq = SQ(**{whichone+'__exact':item})

	# sqs = sqs.filter(sq)
	# raise Exception
	try: return sqs.filter(sq)
	except: return sqs


def list_in_list_search_AND(sqs, args):
	'''(sqs, *args)
	args = [(whichone, [data]), (whichone, [data])]'''
	for whichone, data in args:
		for i, item in enumerate(data):
			try:
				sq = sq & SQ(**{whichone+'__exact':item})
			except:
				sq = SQ(**{whichone+'__exact':item})

	# sqs = sqs.filter(sq)
	# raise Exception
	try: return sqs.filter(sq)
	except: return sqs


@csrf_protect
def search(request, extra_context={}):
	ads_dict = {'results_broker_side_ad':single_ad_picker(6), 'results_client_side_ad':single_ad_picker(4)}


	args = {"title": "Search results"}
	args.update(extra_context)
	args.update(ads_dict)

	if request.user.is_authenticated():
		fin_form = FinancialInfoSearchForm(request.GET)
	else:
		fin_form = FinancialInfoDisabledForm()

	prop_form = PropertySearchForm(request.GET)
	forms_dict = {'mainbox_fin_search': fin_form,\
					'mainbox_prop_search': prop_form}
	

	# this Q should only be ajax, or at most work with only companies
	q = request.GET.get('q')
	if q:
		args.update({'navbar_search': NavBarSearch(request.GET)})
		companies = SearchQuerySet().models(Company).filter(SQ(content=('*'+q+'*')) | SQ(content__startswith=q))
		args.update({"results": companies})
		args.update(select2_dict)
		args.update(forms_dict)
		return render_to_response('search/results.html', args, context_instance=RequestContext(request))

	# re-showing the fields 
	location_list = request.GET.getlist('location')
	try:
		selected_regions = [x.split('_')[1] for x in location_list if x.startswith('region_')]
	except:
		pass
	try:
		selected_countries = [x.split('_')[1] for x in location_list if x.startswith('country_')]
	except:
		pass
	try:
		selected_states = [x.split('_')[1] for x in location_list if x.startswith('state_')]
	except:
		pass
	try:
		selected_commodities = [x for x in request.GET.getlist('commodities')]
	except:
		pass

	selected_status = request.GET.getlist('status')

	selected_estimate = request.GET.get('estimate')
	args.update({'selected_regions': selected_regions, 'selected_countries':selected_countries, 'selected_states':selected_states,\
				'selected_status':selected_status, 'selected_estimate':selected_estimate, 'YNtuple': ['Y', 'N'], 'selected_commodities': selected_commodities})
	# end re-shwoing

	# start search logic
	sqs = SearchQuerySet()

	if prop_form.is_bound and prop_form.is_valid() and selected_status and 'A' not in selected_status:
		pass
		# status
		sqs = list_in_list_search(sqs, [('status', selected_status)])


	# commodity
	sqs = list_in_list_search_AND(sqs, [('commodities', request.GET.getlist('commodities'))])

	# estimate
	if selected_estimate and 'A' not in selected_estimate:
		sqs = sqs.filter(SQ(estimate=selected_estimate) | SQ(estimate='A'))

	#location
	sqs = list_in_list_search(sqs, [('regions', selected_regions), ('countries', selected_countries), ('provinces', selected_states)])

	# Financial Info
	if fin_form.is_bound and fin_form.is_valid():
		sqs = financial_info_search(sqs, fin_form)
	# end search logic

	# raise Exception
	args.update(select2_dict)
	args.update(forms_dict)
	args.update({"results": sqs.models(Company)})
	return render_to_response('search/results.html', args, context_instance=RequestContext(request))


def navbar_ajax_search(request):
	pass

myproject/apps/search/templates/search/results.html
{% extends "base.html" %}
{% load staticfiles %}
{% block CSS %}
	<link href="{% static 'stylesheets/select2.css' %}" rel="stylesheet" type="text/css">
	<link href="{% static 'stylesheets/DT_bootstrap.css' %}" rel="stylesheet">
	<link href="{% static 'stylesheets/docs_searchbox.css' %}" rel="stylesheet">
	<link href="{% static 'stylesheets/docs_resultspage.css' %}" rel="stylesheet">
	<style>
		{% if not user.is_authenticated %}
			.hidden-fin-info{
				border: 1px dashed gray;
				background-color: #eeeeee !important;
			}
		{% endif %}
	</style>
{% endblock %}

{% block content %}
	<div class="container">
		<!-- change results -->
		<div class="row-fluid">
			<!-- <div class="span12 well">
				You have searched for : ... -->
				<!-- <a class="btn btn-success" href="#changesearch" data-toggle="modal">Change search</a> -->
			<!-- </div>  -->
			<!-- change search modal -->
			<div id="changesearch" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 id="myModalLabel">Change the search criteria</h4>
				</div>
				<form class="form-horizontal">
					<div class="modal-body">
						{% include "searchbox.html" %}
						<div class="modal-footer-mobile pull-right">
							<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
							<button type="submit" class="btn btn-primary">Search</button>
						</div>
					</div>

					<div class="modal-footer">
						<button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
						<button type="submit" class="btn btn-primary">Search</button>
					</div>
				</form>
			</div>
		</div>
		<div class="row-fluid">
			<!-- THE SEARCH results -->
			<div class="span9">
				{% if not user.is_authenticated %}
					<p class="alert">To see financial info in search results you need to <a href="#signin" data-toggle="modal">login</a>. 
					If you don't have an account, <a href="#signup" data-toggle="modal">sign up</a>! It's free!</p>
				{% endif %}
				<table class="table table-striped table-hover" id="results">
					<thead>
						<tr>
							<th class="table-sort-header">Sort</th>
							<th>Tk Symbol</th>
							<th>Name</th>
							<th>Price</th>
							<th>Volume</th>
							<th>Market Cap</th>
							<th>Shares Outs.</th>
							<th>52 wk low/high</th>

							<th class="table-sort-header">Volume</th>
							<th class="table-sort-header">Market Cap</th>
							<th class="table-sort-header">Shares Outs.</th>
							<th class="table-sort-header">52 wk low/high</th>
						</tr>
					</thead>
					<tbody class="search-results">
						{% for result in results %}
							<tr>
								{% if user.is_authenticated %}
									{{ result.rendered_auth|safe }}
								{% else %}
									{{ result.rendered_notauth|safe }}
								{% endif %}
								
							</tr>
						{% endfor %}
					</tbody>
				</table>
				<em>Quote data delayed 15 minutes</em>
				<a class="btn btn-success" href="#changesearch" data-toggle="modal">Change search critera</a>
			</div>

			<!-- the side ad -->
			<div class="span3">
				{% if results_client_side_ad %}
				<div class="row-fluid">
					<div class="span12">
						<a href="/msadtrackr/{{ results_client_side_ad.pk }}/alkjsdhf7w6laksjf8389/" target="_blank"><img src="/media/{{ results_client_side_ad.picture }}" alt=""></a>
					</div>
				</div>
				{% endif %}
				{% if results_broker_side_ad %}
				<div class="row-fluid">
					<div class="span12">
						<a href="/msadtrackr/{{ results_broker_side_ad.pk }}/adsfu721yoflaiufialwfku/" target="_blank"><img src="/media/{{ results_broker_side_ad.picture }}" alt=""></a>
					</div>
				</div>
				{% endif %}
			</div>
		</div>
	</div>
{% endblock %}
{% block JS %}
	<script src="{% static 'javascript/jquery.dataTables.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'javascript/DT_bootstrap.js' %}" type="text/javascript"></script>
	<script src="{% static 'javascript/select2.js' %}" type="text/javascript"></script>
	<script src="{% static 'javascript/humanize.js' %}" type="text/javascript"></script>
{% endblock %}
{% block jQuery %}
	<script type="text/javascript">
		$(document).ready(function() {

			jQuery.extend( jQuery.fn.dataTableExt.oSort, {
				"formatted-num-pre": function ( a ) {
					a = (a==="-") ? 0 : a.replace( /[^\d\-\.]/g, "" );
					return parseFloat( a );
				},
			 
				"formatted-num-asc": function ( a, b ) {
					return a - b;
				},
			 
				"formatted-num-desc": function ( a, b ) {
					return b - a;
				}
			} );

			jQuery.extend( jQuery.fn.dataTableExt.oSort, {
				"title-string-pre": function ( a ) {
					try{
						s = parseFloat(a.match(/title="(.*?)"/)[1].toLowerCase());
					}
					catch(err){
						s = ''
					}
					return s
				},
			 
				"title-string-asc": function ( a, b ) {
					return a - b;
				},
			 
				"title-string-desc": function ( a, b ) {
					return b - a;
				}
			} );


			if (($("body").width() > 767)){
				$("#id_commodities, #location").select2();
			} else if(!( (/iPhone|iPod|iPad|Android|BlackBerry/).test(navigator.userAgent) )){
				$("#id_commodities, #location").select2();
			}

			$premiums = $('.premium-sort');
			var randomIndex = Math.floor(Math.random() * $premiums.length);
			$($premiums[randomIndex]).prepend('0');
			
			$('#results').dataTable({
				"aoColumns":[null, null, null, { "sType": "formatted-num" }, { "sType": "title-string" }, { "sType": "title-string" }, { "sType": "title-string" }, { "sType": "title-string" }],
				"oLanguage": {
					"sSearch": "Filter:",
					"sInfo": "Showing _START_ to _END_ of _TOTAL_ results",
					"sInfoEmpty": "Search did not match any results",
				},
				"fnInitComplete": function(oSettings, json) {
						// sponser color
						$("tbody.search-results tr:nth-child(1) > td").addClass('search-sponser');
						$(".search-sponser.premium-client:nth-child(2)").append(" <a class='my-tooltip' href='#' data-toggle='tooltip' data-title='premium profile' data-placement='bottom' style='color: black;'><i class='icon-info-sign'></i></a>");
						$('.my-tooltip').tooltip();
					},
			});

			$("#status_all").change(function(){
				if ($(this).prop('checked')){
					$("input[name=status]").prop({"checked": true, "disabled": true});
				} else{
					$("input[name=status]").prop({"checked": false, "disabled": false});
				}
			});
		});
	</script>
{% endblock %}